<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />

<title>Welcome to Islamic Center of Bloomington Normal, IL</title>

<link rel="icon" type="image/ico" href="Images/favicon.ico"></link> 
<link rel="shortcut icon" href="Images/favicon.ico"></link>

<link rel="stylesheet" href="styles/main.css" type="text/css">
<link rel="stylesheet" href="styles/nav.css" type="text/css">
<link rel="stylesheet" href="styles/custom.css" type="text/css">
<link rel="stylesheet" href="styles/jssor-custom.css" type="text/css">

<script type="text/javascript" src="http://www.jssor.com/script/jquery-1.9.1.min.js"></script>
<script type="text/javascript" src="script/jssor.slider.min.js"></script>
<!-- use jssor.slider.min.js instead for release -->

<script type="text/javascript" src="script/jssor-custom.js"></script>
	
</head>
<body class="body-style">
<?php include "includes/script_include.php" ?>
<div id="maincontainer" class="<?=$shadow_class?>">

<!--
<div id="topsection">
	<div class="innertube">
		<h1>CSS Fixed Layout #3.1- (Fixed-Fixed-Fixed)</h1>
	</div>
</div>
-->


 <div id="header">
   <div class="bgleft">
      <div class="bgright">
         <div class="bgbl"></div>
      </div>
   </div>
 </div>

<style> 
	#panel, #flip {
		padding: 5px;
		text-align: center;
		background-color: #e5eecc;
		border: solid 1px #c3c3c3;
	}

	#panel {
		padding: 50px;
		display: none;
	}
</style>

<script> 
	$(document).ready(function(){
		$("#flip").click(function(){
			$("#panel").slideToggle("slow");
		});
	});
</script>

<?php include "includes/menu_include.php" ?>
	
<!--	
<div id="flip">Click to slide down panel</div>
<div id="panel"> 
	<p align=justify style="padding: 13px;"> 
	<i>

	The Islamic Circle of Bloomington/Normal is appalled at this mass shooting at the Inland Regional Center in San Bernardino and strongly condem all terror attacks. Our condolences and thoughts are with the families of the victims of this senseless shooting and we pray for the speedy recovery for those that are wounded.<br/><br/>

	The Islamic Center of Bloomington/Normal strongly condemns the terrorist attacks in Paris. Our thoughts and prayers go out to the people affected by these senseless acts of violence. 
	<br/>
	</i>
	The loss of innocent lives, especially on a mass scale is devastating to all people of conscience. This kind of violence is inhuman and barbaric and is not justifiable by any religion. The terrorists claiming to believe in our faith are unilaterally distorting the true spirit of Islam. The Quran states <a href="http://www.qtafsir.com/index.php?option=com_content&task=view&id=786&Itemid=60">"He who kills one person kills all humanity."</a> We stand in solidarity with the victims, the first responders, and all of the people of France"

	<br/>

	ICBN participates in <a href="http://m.pantagraph.com/news/local/article_132b6cb2-5dec-51ac-8dd3-1b2041b23a27.html?mobile_touch=true">peace vigil</a> held in uptown normal
	</p>
</div>
-->

<!--slider -->

    <!-- #region Jssor Slider Begin -->
    <!-- Generated by Jssor Slider Maker Online. -->
    <!-- This demo works with jquery library -->
	
    <!-- Caption Style -->
    <style> 
        .captionOrange, .captionBlack
        {
            color: #fff;
            font-size: 20px;
            line-height: 30px;
            text-align: left;
            //border-radius: 3px;
			border-top-right-radius: 2em;
			border-bottom-right-radius: 2em;
        }
        .captionOrange
        {
            background: #EB5100;
            background-color: rgba(235, 81, 0, 0.6);
        }
        .captionBlack
        {
        	font-size:16px;
            background: #000;
            background-color: rgba(0, 0, 0, 0.4);
        }
        a.captionOrange, A.captionOrange:active, A.captionOrange:visited
        {
        	color: #ffffff;
        	text-decoration: none;
        }
        a.captionOrange:hover
        {
            color: #eb5100;
            text-decoration: underline;
            background-color: #eeeeee;
            background-color: rgba(238, 238, 238, 0.7);
        }
        .bricon
        {
            background: url(../img/browser-icons.png);
        }
    </style>

<!--
//space for slider include
-->

<div id="contentwrapper">
<div id="contentcolumn">


<?php include "includes/mainbody_include.php" ?>


<!-- do not delete after this.. -->
</div>
</div>


<div id="leftcolumn">
<div class="innertube">


</div>

</div>

<div id="rightcolumn">
<div class="righttube">

<?php include "includes/rightnav_body.php" ?>
</div>
</div>

<div id="footer">
	
<?php include "includes/footer_body.php" ?>

			
</div>

</div>
</body>
</html>
